#!/usr/bin/env python

'''
@author: Viktor Petersson
For the latest version, visit https://github.com/vpetersson/munin_zendesk

This plugin depends on zendesk_tickets for data.
'''

import json, sys, os, pickle


if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print 'yes'

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    print 'graph_title Zendesk Closed Tickets'
    print 'graph_vlabel count'
    print 'graph_category zendesk'
    print 'total_closed.label Closed Tickets'
    print 'total_closed.type GAUGE'
    print 'graph_args --base 1000'


else:
    # Fetch the result from the local cache
    localcache = open('/tmp/zendesk_tickets.pkl', 'rb')
    result = pickle.load(localcache)
    ticketsClosed = result['ticketsClosed']
    localcache.close()
        
    # Report the result
    print 'total_closed.value ' + str(ticketsClosed)

