#!/usr/bin/env python

'''
@author: Viktor Petersson
For the latest version, visit https://github.com/vpetersson/munin_zendesk

This plugin depends on zendesk_tickets for data.
'''

import json, sys, os, pickle, zendesk_helper

cache_folder = zendesk_helper.cache_folder
cache_file_path = os.path.join(cache_folder, 'zendesk_tickets.pkl')

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print 'yes'

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    print 'graph_title Zendesk Closed Tickets'
    print 'graph_vlabel count'
    print 'graph_category zendesk'
    print 'total_closed.label Closed Tickets'
    print 'total_closed.type GAUGE'
    print 'graph_args --base 1000'


else:
    # Fetch the result from the local cache
    cache_file = open(cache_file_path, 'rb')
    result = pickle.load(cache_file)
    tickets_closed = result['ticketsClosed']
    cache_file.close()
        
    # Report the result
    print 'total_closed.value ' + str(tickets_closed)

