#!/usr/bin/env python

'''
@author: Viktor Petersson
Munin-plugin for plotting data from Zendesk. Includes code from Adam Panzer.
'''

import pycurl, cStringIO, json, sys, os

credentials = os.environ['credentials']
subdomain = os.environ['subdomain']

def pyCurlWrap(pUrl, meth, data):
    buf = cStringIO.StringIO()
    c=pycurl.Curl()
    c.setopt(c.URL, pUrl);
    c.setopt(c.WRITEFUNCTION, buf.write)
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 8)
    if not data == "null":
        c.setopt(c.POSTFIELDS, data)
    c.setopt(c.FOLLOWLOCATION, True)
    c.setopt(c.MAXREDIRS, 10)
    c.setopt(c.USERPWD, credentials)
    c.setopt(c.CUSTOMREQUEST, meth)
    c.setopt(c.HTTPHEADER, ['Content-type: application/json'])
    c.perform()
    result = buf.getvalue()
    buf.close()
    return result;

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print 'yes'

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    print 'graph_title Zendesk Tickets'
    print 'graph_vlabel count'
    print 'graph_category zendesk'
    print 'total_open.label Open Tickets'
    print 'total_open.type GAUGE'
    print 'total_closed.label Closed Tickets'
    print 'total_closed.type GAUGE'
    print 'total_new.label New Tickets'
    print 'total_new.type GAUGE'    
    print 'total_pending.label Pending Tickets'
    print 'total_pending.type GAUGE'
    print 'total_solved.label Solved Tickets'
    print 'total_solved.type GAUGE'
    print 'graph_args --base 1000'

else:
    # Define variables
    allTickets = []
    ticketsOpen = 0
    ticketsClosed = 0
    ticketsNew = 0
    ticketsPending = 0
    ticketsSolved = 0
    
    try:
        query = json.loads(pyCurlWrap("https://"+str(subdomain)+".zendesk.com/api/v2/tickets.json", "GET", "null"))
        if query == "Couldn't authenticate you":
            print 'Zendesk rejected your credentials.'
            exit
        
        # Ops, there's another page with tickets. Let's keep fetching.
        while query['next_page'] != None:
            fetchMore = json.loads(pyCurlWrap(str(query['next_page']), "GET", "null"))
            allTickets += fetchMore['tickets']
            query = fetchMore

        if allTickets:
            tickets = allTickets
        else:
            tickets = query['tickets']
        
        # Do the math
        for i in tickets:
            if i['status'] == 'open':
                ticketsOpen += 1
            elif i['status'] == 'closed':
                ticketsClosed += 1
            elif i['status'] == 'new':
                ticketsNew += 1
            elif i['status'] == 'pending':
                ticketsPending += 1
            elif i['status'] == 'solved':
                ticketsSolved += 1
    
        # Report the result
        print 'total_open.value: ' + str(ticketsOpen)
        print 'total_closed.value: ' + str(ticketsClosed)
        print 'total_new.value: ' + str(ticketsNew)
        print 'total_pending.value: ' + str(ticketsPending)
        print 'total_solved.value: ' + str(ticketsSolved)

    except:
        print 'Unable to connect to Zendesk.'